export const homepage = {
    SectionHeader0: "Land Connected",
    SectionDescription0: "Why get stressed looking for a SIM card, when you can land connected,  travel like a king and not have to worry about expensive roaming bills.",
    SectionHeader1: "Welcome To eSIM PALACE",
    SectionDescription1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dignissim cursus nisl, id ultricies est. Donec rhoncus orci eget convallis volutpat. Nam massa augue, elementum quis arcu et, commodo pretium nunc. Proin in semper ipsum, et ultricies nisi. Curabitur quis ultrices nibh, Consequat tellus. Ut at fringilla purus, sed condimentum lectus. Sed sit amet nisl hendrerit metus auctor tempus eget non nisl. Nunc sagittis"
};

export const about = {
    SectionHeader0: "eSim Palace",
    SectionDescription0: "Travel like a king and never worry about finding a new sim card once you land and expensive roaming rates ever again. Explore the Palace and enjoy the royal experience from here on",
    SectionHeader1: "Welcome To eSIM PALACE",
    SectionDescription1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dignissim cursus nisl, id ultricies est. Donec rhoncus orci eget convallis volutpat. Nam massa augue, elementum quis arcu et, commodo pretium nunc. Proin in semper ipsum, et ultricies nisi. Curabitur quis ultrices nibh, Consequat tellus. Ut at fringilla purus, sed condimentum lectus. Sed sit amet nisl hendrerit metus auctor tempus eget non nisl. Nunc sagittis",

    Digital: "An eSIM is an industry-standard digital SIM that allows you to activate a cellular plan from your carrier without having to use a physical",
    Fixed: "Fixed costs include any number of expenses, including rental and lease payments, certain salaries, insurance, property taxes, interest expenses.",
    Easy: "eSIM offers many benefits while you travel abroad. It's more secure than a physical SIM because it can't be removed if your iPhone is lost",
}

export const contact = {
    SectionHeader0: "Stay in Touch",
    SectionDescription0: "Contacting us or contacting your loved ones has never been easier. Search or scroll below and find the contacts or ability to contact you have been searching for.",
    SectionHeader1: "Contact eSim Palace",
    SectionDescription1: "We are available around the clock to answer all of your questions, whenever you need us. If you have any support questions, please try our support page first as 99% of our customers find the answer they are looking for within three clicks.",
    Support: "The condition of being supported.  assistance provided by a company to users of its products. customer support. one that supports.",
    Corporate: "A corporation is an organization usually group of people company authorized by the state to act as a single entity and recognized as such in law",
}

export const packages = {
    SectionHeader0: "Data For\nEverywhere",
    SectionDescription0: "Enjoy data wherever you are or are going at the click of a button.",
    SectionHeader1: "All our packages",
    SectionDescription1: "See below for all our packages listed by country and region. Find data for everywhere you want to go.",
}

export const support = {
    SectionHeader0: "Support When You Need It Most",
    SectionDescription0: "Just like our data, we’re always here to help. See below for answers that we are sure will help you solve your problems and get online ASAP.",
    SectionHeader1: "Support",
    SectionDescription1: "See below for answers to all our leading questions, but don’t hesitate to contact us if you need more help.",
    installations: ["When should I install my eSIM?", "How do I install my eSIM? (iOS)", "How do I install my eSIM? (Android)", "How do I install my eSIM? (Pixel)"],
    install_descriptions: [
        "To ensure a smooth setup process, we recommend installing and activating your eSIM just before your departure as installation requires an internet connection. However, if you prefer, you can wait until you arrive in the country to activate your eSIM using Wi-Fi.Once your eSIM is installed, you have the option to turn it off. Activation of the package only occurs when you use your eSIM in regions where it is eligible for connection. ",
        "Scan the QR code provided to you on the checkout page or email confirmation\nTap Mobile Plan\nAccept and continue on all prompts.\nOnce within an eligible country for your eSIM package switch mobile data to your eSIM. Settings -> Mobile Data -> Mobile Data and set it to your eSIM.\nWe recommend leaving your Default Voice Line set to your Home provider so that you can continue to receive calls using Voice over Wi-Fi. Please check availability and charges with your service provider.\nTurn Roaming on for your eSIM. Settings -> Mobile Data -> Your eSIM under SIMs -> Toggle Data Roaming to on.\n",
        "Scan the QR code provided to you on the checkout page or email confirmation.\nClick on the eSIM popup – Add this plan to connect to a new mobile network.\nAccept and continue on all prompts.\nOnce within an eligible country for your eSIM package switch mobile data to your eSIM. Settings -> Connections -> Sim Manager-> Mobile Data and set it to your eSIM\n We recommend leaving Calls and Messages set to your Home provider so that you can continue to receive calls using Voice over Wi-Fi and Text/SMS for One Time Passwords. Please check availability and charges with your service provider.\nTurn Roaming on for your eSIM. Settings -> Connections -> Mobile networks and toggle on Data Roaming.\n",
        "Scan the QR code provided to you on the checkout page or email confirmation.\nClick on the LPA popup.\nAccept and continue on all prompts.\nOnce within an eligible country for your eSIM package switch mobile data to your eSIM. Settings -> Network & internet -> SIMs -> Turn on if not already switched on ->  Toggle on Mobile Data, Toggle on Roaming \nWe recommend leaving your Default Voice Line set to your Home provider so that you can continue to receive calls using Voice over Wi-Fi. Please check availability and charges with your service provider.\n"
    ],
    troubleshooting: ["What happens if I can’t connect with my eSIM on my phone? (iOS)","What happens if I can’t connect with my eSIM on my phone? (Android)","What happens if I can’t connect with my eSIM on my phone? (Pixel)"],
    troubleshooting_descriptions: [
        "⦁	To turn on the Data Roaming\n        ⦁	Go to Settings on your device\n        ⦁	Go to Mobile Data\n        ⦁	Select your eSIM under SIMs\n        ⦁	Toggle on Data Roaming.\n⦁	To update the APN settings:\n        ⦁	Go to Settings on your device\n        ⦁	Go to Mobile Data \n        ⦁	Select your eSIM under SIMs\n        ⦁	Go to Mobile Data Network\n        ⦁	Under MOBILE DATA, change the APN to globaldata (all lower case, all one word, no space before or after.)\n        ⦁	Leave the other fields blank",
        "⦁	To turn on the Data Roaming:\n        ⦁	Go to Settings on your device\n        ⦁	Click Connections\n        ⦁	Click Mobile networks\n        ⦁	Toggle Roaming to On\n⦁	To update the APN settings:\n        ⦁	Go to Settings on your device\n        ⦁	Go to the Network & Internet section\n        ⦁	Go to Mobile Networks\n        ⦁	Go to Access Point Names\n        ⦁	Tap “+” or “ADD”\n        ⦁	Type the new APN settings as written in the eSIM installation details under APN (all lower case, all one word)\n        ⦁	Tap save\n        ⦁	Leave the other fields blank\n⦁	Ensure you do not have a Data Limit set\n        ⦁	Go to Settings on your device\n        ⦁	Connections\n        ⦁	Go to Data Usage\n        ⦁	Bill cycle and Data Warning\n        ⦁	Toggle off Set Data Limit\n",
        "⦁	To turn on the Data Roaming\n        ⦁	Go to Settings on your device.\n         ⦁	Click on Network & internet\n        ⦁	Click on SIMs and Turn on if not already switched on  \n        ⦁	Toggle on Mobile Data\n        ⦁	Toggle on Roaming\n⦁	To update the APN settings:\n        ⦁	Go to Settings on your device.\n         ⦁	Click on Network & internet\n        ⦁	Click on SIMs.\n        ⦁	Scroll down to Access Point Names.\n        ⦁	Click Play Internet.\n        ⦁	Change the APN to globaldata (all lower case, all one word, no space before or after.)\n        ⦁	Leave the other fields blank\n        ⦁	Click the 3 dots menu top right\n        ⦁	Click Save.\n⦁	Ensure you do not have a data limit set\n        ⦁	Go to Settings on your device. \n        ⦁	Click on Network & internet\n        ⦁	Click on SIMs and Turn on if not already switched on  \n        ⦁	Click Data warnings & limit\n        ⦁	Toggle off set data limit\n",
    ],
    support: ["What is my ICCID and where do I find it? (iOS)","What is my ICCID and where do I find it? (Android)","What is my ICCID and where do I find it? (Pixel)"],
    support_descriptions: [
        "When you contact support, they will ask you for the ICCID number of your eSIM. The ICCID is like a special code or ID unique to your eSIM. It helps support identify your eSIM quickly so that they can provide you with the assistance you need promptly.\n\nThe ICCID can be found on your purchase confirmation email, within your profile on our website or app and on your device:\n        ⦁	To go Settings on your device\n        ⦁	Click General\n        ⦁	Click About\n        ⦁	Scroll down to the bottom\n        ⦁	You should see your eSIM listed\n        ⦁	Long press on your ICCID to copy it.",
        "When you contact support, they will ask you for the ICCID number of your eSIM. The ICCID is like a special code or ID unique to your eSIM. It helps support identify your eSIM quickly so that they can provide you with the assistance you need promptly.\n\nThe ICCID can be found on your purchase confirmation email, within your profile on our website or app and on your device:\n\n        ⦁	To go Settings on your device\n        ⦁	Click on Connection Manager\n        ⦁	Click on your eSIM\n        ⦁	Click more information\n        ⦁	Your ICCID will be shown on screen\n",
        "When you contact support, they will ask you for the ICCID number of your eSIM. The ICCID is like a special code or ID unique to your eSIM. It helps support identify your eSIM quickly so that they can provide you with the assistance you need promptly.\n\nThe ICCID can be found on your purchase confirmation email, within your profile on our website or app and on your device:\n\n        ⦁	To go Settings on your device\n        ⦁	Scroll down to the bottom and click About phone\n        ⦁	Scroll down to and click on SIM status (sim slot 2)\n        ⦁	Your ICCID will be shown on screen near the bottom.\n",
    ],
    general: ["Can I use tethering (creating a personal hotspot)? (iOS)","Can I use tethering (creating a personal hotspot)? (Android)","Can I use tethering (creating a personal hotspot)? (Pixel)","Can I install the same eSIM on multiple devices?","When does my eSIM data plan start?","Can I make calls with my eSIM?","What happens to my SMS when I use a Data eSIM?","Can I buy an eSIM for multiple countries?"],
    general_descriptions: [
        'Yes, you can use your personal hotspot with your eSIM as long as it is supported by your device and the network.\n\n        ⦁	Go to Settings\n        ⦁	Personal Hotspot\n        ⦁	Toggle on “Allow Others to Join”\n',
        'In order to turn on your device’s hotspot, please follow these steps: \n\n        ⦁	From the Home screen, head to Settings on your device (pull down the notification bar and hit the gear-shaped Settings button) \n        ⦁	Go to Network & Internet \n        ⦁	Tap “Hotspot & tethering.”\n        ⦁	Tap “Wi-Fi hotspot” and turn on “Wi-Fi hotspot.”\n',
        'In order to turn on your device’s hotspot, please follow these steps: \n\n        ⦁	Go to Settings on your device. \n        ⦁	Go to Network & Internet \n        ⦁	Tap “Hotspot & tethering.”\n        ⦁	Tap “Wi-Fi hotspot” and turn on “Wi-Fi hotspot.”\n',
        'No, you can’t install the same eSIM on multiple devices.\n\n        Your eSIM can only be installed on one device, and most eSIMs can be installed only once. This means that if you remove the eSIM from your device, it will not be possible to install it again.\n',
        'Your eSIM data plan begins the moment you activate it on your phone and are within an eligible region for your package,\n\nOnly once activate does the number of days in your plan will start counting down.\n\nIn short, the number of days in the plan will start counting down when you activate your eSIM in an eligible country and not when you install it.\n',
        'Your eSIM is data only, and so you won’t be able to make traditional calls using it. You can however use it to make calls on your favourite apps including WhatsApp, Skype, Facetime and other VoIP services. You will still be able to use you regular cellular provider for voice using Voice Over Wi-Fi or Voice over Mobile.\nPlease check the charges for these with your home cellular carrier.',
        'Your eSIM is data only, You can still receive SMS from your home carrier if your home cellular plan remains enabled.\nPlease check the charges for these with your home cellular carrier.',
        'Yes, we offer several multi-country packages. These are perfect if you’re travelling to a number of different countries on one trip.\nEach time you enter a new country, your eSIM will automatically connect to a network in that country.\nSearch for your ideal region on our website and enjoy the benefits on landing connected each time you land in a new country.',
    ],
    about: ["What is an eSIM?","How long does my Data eSIMs last?","Can I add more Data to my eSIM?"],
    about_descriptions: [
        "An eSIM is one of the cheapest and most convenient way to use your device abroad. An eSIM is a virtual sim card. The difference between an eSIM and a traditional SIM card, is that you download the eSIM to your phone instead of physically putting in a new SIM card into your device. An eSIM acts just like a traditional SIM card . The eSIM works the same way as a traditional SIM card, but you don't need a physical SIM card to use it. ... More and more smartphones, tablets and laptops are equipped with an eSIM card.",
        "Your eSIM will last until it uses up all of its data or reaches the end of the package duration terms. Please make sure before purchasing your eSIM that you select the correct package for your needs.",
        "Yes, when your date runs low, or runs out you will be able to Top Up your eSIM buy visiting our site and adding a new package to your ESIM"
    ],
    titles: [
        ["When should I install my eSIM?", "How do I install my eSIM? (iOS)", "How do I install my eSIM? (Android)", "How do I install my eSIM? (Pixel)"],
        ["What happens if I can’t connect with my eSIM on my phone? (iOS)","What happens if I can’t connect with my eSIM on my phone? (Android)","What happens if I can’t connect with my eSIM on my phone? (Pixel)"],
        ["What is my ICCID and where do I find it? (iOS)","What is my ICCID and where do I find it? (Android)","What is my ICCID and where do I find it? (Pixel)"],
        ["Can I use tethering (creating a personal hotspot)? (iOS)","Can I use tethering (creating a personal hotspot)? (Android)","Can I use tethering (creating a personal hotspot)? (Pixel)","Can I install the same eSIM on multiple devices?","When does my eSIM data plan start?","Can I make calls with my eSIM?","What happens to my SMS when I use a Data eSIM?","Can I buy an eSIM for multiple countries?"],
        ["What is an eSIM?","How long does my Data eSIMs last?","Can I add more Data to my eSIM?"],
    ],
    descriptions: [
        [
            "To ensure a smooth setup process, we recommend installing and activating your eSIM just before your departure as installation requires an internet connection. However, if you prefer, you can wait until you arrive in the country to activate your eSIM using Wi-Fi.Once your eSIM is installed, you have the option to turn it off. Activation of the package only occurs when you use your eSIM in regions where it is eligible for connection. ",
            "Scan the QR code provided to you on the checkout page or email confirmation\nTap Mobile Plan\nAccept and continue on all prompts.\nOnce within an eligible country for your eSIM package switch mobile data to your eSIM. Settings -> Mobile Data -> Mobile Data and set it to your eSIM.\nWe recommend leaving your Default Voice Line set to your Home provider so that you can continue to receive calls using Voice over Wi-Fi. Please check availability and charges with your service provider.\nTurn Roaming on for your eSIM. Settings -> Mobile Data -> Your eSIM under SIMs -> Toggle Data Roaming to on.\n",
            "Scan the QR code provided to you on the checkout page or email confirmation.\nClick on the eSIM popup – Add this plan to connect to a new mobile network.\nAccept and continue on all prompts.\nOnce within an eligible country for your eSIM package switch mobile data to your eSIM. Settings -> Connections -> Sim Manager-> Mobile Data and set it to your eSIM\n We recommend leaving Calls and Messages set to your Home provider so that you can continue to receive calls using Voice over Wi-Fi and Text/SMS for One Time Passwords. Please check availability and charges with your service provider.\nTurn Roaming on for your eSIM. Settings -> Connections -> Mobile networks and toggle on Data Roaming.\n",
            "Scan the QR code provided to you on the checkout page or email confirmation.\nClick on the LPA popup.\nAccept and continue on all prompts.\nOnce within an eligible country for your eSIM package switch mobile data to your eSIM. Settings -> Network & internet -> SIMs -> Turn on if not already switched on ->  Toggle on Mobile Data, Toggle on Roaming \nWe recommend leaving your Default Voice Line set to your Home provider so that you can continue to receive calls using Voice over Wi-Fi. Please check availability and charges with your service provider.\n"
        ],
        [
            "⦁	To turn on the Data Roaming\n        ⦁	Go to Settings on your device\n        ⦁	Go to Mobile Data\n        ⦁	Select your eSIM under SIMs\n        ⦁	Toggle on Data Roaming.\n⦁	To update the APN settings:\n        ⦁	Go to Settings on your device\n        ⦁	Go to Mobile Data \n        ⦁	Select your eSIM under SIMs\n        ⦁	Go to Mobile Data Network\n        ⦁	Under MOBILE DATA, change the APN to globaldata (all lower case, all one word, no space before or after.)\n        ⦁	Leave the other fields blank",
            "⦁	To turn on the Data Roaming:\n        ⦁	Go to Settings on your device\n        ⦁	Click Connections\n        ⦁	Click Mobile networks\n        ⦁	Toggle Roaming to On\n⦁	To update the APN settings:\n        ⦁	Go to Settings on your device\n        ⦁	Go to the Network & Internet section\n        ⦁	Go to Mobile Networks\n        ⦁	Go to Access Point Names\n        ⦁	Tap “+” or “ADD”\n        ⦁	Type the new APN settings as written in the eSIM installation details under APN (all lower case, all one word)\n        ⦁	Tap save\n        ⦁	Leave the other fields blank\n⦁	Ensure you do not have a Data Limit set\n        ⦁	Go to Settings on your device\n        ⦁	Connections\n        ⦁	Go to Data Usage\n        ⦁	Bill cycle and Data Warning\n        ⦁	Toggle off Set Data Limit\n",
            "⦁	To turn on the Data Roaming\n        ⦁	Go to Settings on your device.\n         ⦁	Click on Network & internet\n        ⦁	Click on SIMs and Turn on if not already switched on  \n        ⦁	Toggle on Mobile Data\n        ⦁	Toggle on Roaming\n⦁	To update the APN settings:\n        ⦁	Go to Settings on your device.\n         ⦁	Click on Network & internet\n        ⦁	Click on SIMs.\n        ⦁	Scroll down to Access Point Names.\n        ⦁	Click Play Internet.\n        ⦁	Change the APN to globaldata (all lower case, all one word, no space before or after.)\n        ⦁	Leave the other fields blank\n        ⦁	Click the 3 dots menu top right\n        ⦁	Click Save.\n⦁	Ensure you do not have a data limit set\n        ⦁	Go to Settings on your device. \n        ⦁	Click on Network & internet\n        ⦁	Click on SIMs and Turn on if not already switched on  \n        ⦁	Click Data warnings & limit\n        ⦁	Toggle off set data limit\n",
        ],
        [
            "When you contact support, they will ask you for the ICCID number of your eSIM. The ICCID is like a special code or ID unique to your eSIM. It helps support identify your eSIM quickly so that they can provide you with the assistance you need promptly.\n\nThe ICCID can be found on your purchase confirmation email, within your profile on our website or app and on your device:\n        ⦁	To go Settings on your device\n        ⦁	Click General\n        ⦁	Click About\n        ⦁	Scroll down to the bottom\n        ⦁	You should see your eSIM listed\n        ⦁	Long press on your ICCID to copy it.",
            "When you contact support, they will ask you for the ICCID number of your eSIM. The ICCID is like a special code or ID unique to your eSIM. It helps support identify your eSIM quickly so that they can provide you with the assistance you need promptly.\n\nThe ICCID can be found on your purchase confirmation email, within your profile on our website or app and on your device:\n\n        ⦁	To go Settings on your device\n        ⦁	Click on Connection Manager\n        ⦁	Click on your eSIM\n        ⦁	Click more information\n        ⦁	Your ICCID will be shown on screen\n",
            "When you contact support, they will ask you for the ICCID number of your eSIM. The ICCID is like a special code or ID unique to your eSIM. It helps support identify your eSIM quickly so that they can provide you with the assistance you need promptly.\n\nThe ICCID can be found on your purchase confirmation email, within your profile on our website or app and on your device:\n\n        ⦁	To go Settings on your device\n        ⦁	Scroll down to the bottom and click About phone\n        ⦁	Scroll down to and click on SIM status (sim slot 2)\n        ⦁	Your ICCID will be shown on screen near the bottom.\n",
        ],
        [
            'Yes, you can use your personal hotspot with your eSIM as long as it is supported by your device and the network.\n\n        ⦁	Go to Settings\n        ⦁	Personal Hotspot\n        ⦁	Toggle on “Allow Others to Join”\n',
            'In order to turn on your device’s hotspot, please follow these steps: \n\n        ⦁	From the Home screen, head to Settings on your device (pull down the notification bar and hit the gear-shaped Settings button) \n        ⦁	Go to Network & Internet \n        ⦁	Tap “Hotspot & tethering.”\n        ⦁	Tap “Wi-Fi hotspot” and turn on “Wi-Fi hotspot.”\n',
            'In order to turn on your device’s hotspot, please follow these steps: \n\n        ⦁	Go to Settings on your device. \n        ⦁	Go to Network & Internet \n        ⦁	Tap “Hotspot & tethering.”\n        ⦁	Tap “Wi-Fi hotspot” and turn on “Wi-Fi hotspot.”\n',
            'No, you can’t install the same eSIM on multiple devices.\n\n        Your eSIM can only be installed on one device, and most eSIMs can be installed only once. This means that if you remove the eSIM from your device, it will not be possible to install it again.\n',
            'Your eSIM data plan begins the moment you activate it on your phone and are within an eligible region for your package,\n\nOnly once activate does the number of days in your plan will start counting down.\n\nIn short, the number of days in the plan will start counting down when you activate your eSIM in an eligible country and not when you install it.\n',
            'Your eSIM is data only, and so you won’t be able to make traditional calls using it. You can however use it to make calls on your favourite apps including WhatsApp, Skype, Facetime and other VoIP services. You will still be able to use you regular cellular provider for voice using Voice Over Wi-Fi or Voice over Mobile.\nPlease check the charges for these with your home cellular carrier.',
            'Your eSIM is data only, You can still receive SMS from your home carrier if your home cellular plan remains enabled.\nPlease check the charges for these with your home cellular carrier.',
            'Yes, we offer several multi-country packages. These are perfect if you’re travelling to a number of different countries on one trip.\nEach time you enter a new country, your eSIM will automatically connect to a network in that country.\nSearch for your ideal region on our website and enjoy the benefits on landing connected each time you land in a new country.',
        ],
        [
            "An eSIM is one of the cheapest and most convenient way to use your device abroad. An eSIM is a virtual sim card. The difference between an eSIM and a traditional SIM card, is that you download the eSIM to your phone instead of physically putting in a new SIM card into your device. An eSIM acts just like a traditional SIM card . The eSIM works the same way as a traditional SIM card, but you don't need a physical SIM card to use it. ... More and more smartphones, tablets and laptops are equipped with an eSIM card.",
            "Your eSIM will last until it uses up all of its data or reaches the end of the package duration terms. Please make sure before purchasing your eSIM that you select the correct package for your needs.",
            "Yes, when your date runs low, or runs out you will be able to Top Up your eSIM buy visiting our site and adding a new package to your ESIM"
        ],
    ]
}

export const transaction = {
    SectionHeader0: "Data For\nEverywhere",
    SectionDescription0: "Enjoy data wherever you are or are going at the click of a button.",
    SectionHeader1: "Order Confirmation",
    SectionDescription1: "See below for all our packages listed by country and region. Find data for everywhere you want to go.",
}